### ISSUE TITLE
Can't install due to "Invalid Version: undefined" error

### ISSUE THREAD

**Issue by larryh** [mike-north/ember-cli-document-title-northm#67]
Hi,

I just tried to install your fork of ember-cli-document-title and got the error message listed down below. I have also pasted the contents of the `error.dump.nnn.log` file

I try to keep up to date with the latest and greatest Node versions, i.e. past what is supported by Ember. I get identical warnings when I fire up my server in Development, and when I tried to install your addon:

`
WARNING: Node v11.9.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
`

This is just a WARNING, and my code runs fine. But is this warning the reason I cannot install your addon? If so, does this mean I have to back off my Node version? I was going to update to Node v12.0.0, but Ember only supports v10.x.x - which is a pretty big difference. And, like I said, my code runs fine on Node versions greater than what Ember says it "officially" supports on this page: [Node Support](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md)

The error information is down below.

Thanks,
Larry

`
larry@larry-lap:~/RubyMine/BNC$ ember install ember-cli-document-title-northm

WARNING: Node v11.9.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
Invalid Version: undefined

Stack Trace and Error Report: /tmp/error.dump.17c021a73989836e8e5f12107331556b.log

=======================================================================

ENV Summary:

  TIME: Thu Apr 25 2019 09:31:35 GMT-0500 (Central Daylight Time)
  TITLE: ember
  ARGV:
  - /home/larry/.nvm/versions/node/v11.9.0/bin/node
  - /home/larry/.nvm/versions/node/v11.9.0/bin/ember
  - install
  - ember-cli-document-title-northm
  EXEC_PATH: /home/larry/.nvm/versions/node/v11.9.0/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - /home/larry/.nvm/versions/node/v11.9.0/bin
  - /home/larry/RubyMine/BNC/node_modules/.bin
  - /home/larry/.rvm/gems/ruby-2.1.2@stuptues/bin
  - /home/larry/.rvm/gems/ruby-2.1.2@global/bin
  - /home/larry/.rvm/rubies/ruby-2.1.2/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - /home/larry/.rvm/bin
  - /home/larry/.rvm/bin
  PLATFORM: linux x64
  FREEMEM: 6288687104
  TOTALMEM: 16735985664
  UPTIME: 3587
  LOADAVG: 1.1669921875,1.06591796875,1.18017578125
  CPUS:
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3457
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3446
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3487
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3540
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3392
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3453
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3429
  - Intel(R) Core(TM) i7-4800MQ CPU @ 2.70GHz - 3525
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.15.0
  - brotli: 1.0.7
  - cldr: 34.0
  - http_parser: 2.8.0
  - icu: 63.1
  - llhttp: 1.0.1
  - modules: 67
  - napi: 4
  - nghttp2: 1.34.0
  - node: 11.9.0
  - openssl: 1.1.1a
  - tz: 2018e
  - unicode: 11.0
  - uv: 1.25.0
  - v8: 7.0.276.38-node.16
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Invalid Version: undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Invalid Version: undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Invalid Version: undefined
    at new SemVer (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/semver/semver.js:296:11)
    at compare (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/semver/semver.js:585:10)
    at Function.gte (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/semver/semver.js:634:10)
    at findPackageManager.then (/home/larry/RubyMine/BNC/node_modules/ember-cli/lib/tasks/npm-task.js:165:20)
    at tryCatcher (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (/home/larry/RubyMine/BNC/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at processTicksAndRejections (internal/process/next_tick.js:74:9)

========================================================================

`

**Comment by mike-north** [comment]
have you tried deleting your `node_modules` folder and reinstalling your dependencies?

I'd expect any problem relating to dependencies to show up in our testing pipeline, but I don't see any problems. To make sure, I just kicked off [a new test run](https://travis-ci.org/mike-north/ember-api-actions/builds/524534616) to see what happens

**Comment by larryh** [comment]
Hi,

Thanks for the quick reply. I deleted my `node_modules` and `tmp` and `dist` directories and did an `npm install` and then tried `ember install ember-cli-document-title-northm` and got the same error.

This is frustrating because everything else works fine (except for the WARNING) message, and scary because it seems like I am the only one having this problem - which is never a good position to be in. :-(

Any thoughts?

**Comment by larryh** [comment]
Hey Mike,

Good news! I just upgraded ember from 3.8 to 3.9 and was then able to install your addon. And, to top it off, it works like a charm!

Thanks for forking and supporting this addon, which includes your quick reply to me earlier today.

Thanks again,
Larry
